name: 590spring21
channels:
  - conda-forge
dependencies:
  - ipywidgets
  - obspy
  - keras
  - jupyterhub-singleuser
  - jupyter-server-proxy
  - jupyterlab=3
  - jupyter-resource-usage
  - matplotlib
  - nbgitpuller
  - numpy
  - obspy
  - pandas
  - pip=20
  - scipy
