name: 590spring21
channels:
  - conda-forge
dependencies:
  - python=3.9
  - jupyter
  - earthpy
  - folium
  - geopandas
  - matplotlib
  - mongodb
  - pymongo
  - netCDF4
  - numpy
  - pandas
  - pycrs
  - pytorch
  - rasterio
  - scipy
  - scikit-learn
  - shapely
  - xarray
  - ipywidgets
