name: 590spring21_ml
channels:
  - conda-forge
dependencies:
  - python=3.8
  - jupyter
  - jupyterlab
  - geopandas
  - matplotlib
  - numpy
  - pandas
  - pytorch
  - rasterio
  - scipy
  - scikit-learn
  - torchvision
  - xarray
  - tensorflow
  - keras
  - h5py
  - obspy
